name: 24/7 Efteling Storing Checker

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *' # Draait bijvoorbeeld elke 15 minuten

jobs:
  check-storingen:
    runs-on: ubuntu-latest

    steps:
      - name: Code ophalen uit repository
        uses: actions/checkout@v4

      - name: Node.js omgeving instellen
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Voer checker.js uit
        run: node checker.js
        # Als je environment variables gebruikt, voeg ze hier toe:
        # env:
        #   API_KEY: ${{ secrets.MY_API_KEY }}
